# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3"

services:
  # db service
  db:
    container_name: db
    image: postgres:latest
    expose:
      - 5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=!Passw0rd
      - POSTGRES_DB=Inventory
    networks:
      - sql
  
  # web service
  inventory-api:
    networks:
      - sql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    env_file:
      - ./test.env
    restart: always
    expose:
      - 5000
    depends_on:
      - db

  # ningx proxy service
  proxy:
    networks:
      - sql
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - inventory-api

networks:
  sql:
volumes:
  db-data:
