# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    volumes:
      - C:\Users\comsa\code\volumeData\inventoryV:/var/lib/mysql/data

      # - "inventory-db-data:/var/lib/mysql/data"
    networks:
      - sql
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!Passw0rd
    ports:
      - "1433:1433"
    expose:  
      - 1433

  inventory-api:
    networks:
     - sql
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    restart: always 
    ports:
      - "8080:80"
    expose: 
      - 8080
    depends_on:
      - db
    command: 
      - "sleep 2000;" 

networks:
  sql:
volumes:
  inventory-db-data: