# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    volumes:
      -  inventory-db-data:/var/lib/mysql/data

      # - "inventory-db-data:/var/lib/mysql/data"
    networks:
      - sql
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!Passw0rd
    # ports:
    #   - "1433:1433"
    # expose:  
    #   - 1433

  inventory-api:
    networks:
     - sql
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    environment: 
      - ASPNETCORE_URLS=https://+:5001
      # - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=!Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    restart: always 
    ports:
      - "80:5001"
    expose: 
      - 80
    depends_on:
      - db

networks:
  sql:
volumes:
  inventory-db-data: